training:
  batch_size: 32
  num_epochs: 20
  learning_rate: 0.0001

model:
  embed_size: 256
  num_heads: 8
  hidden_dim: 512
  num_layers: 6
  target_channels: 512
  target_size: [20, 20]
  max_seq_length: 50

paths:
  swin_checkpoint: "./checkpoint/feature_extraction/swinv2-large-patch4-window12to24-192to384-22kto1k-ft.pth"
  yolo_checkpoint: "./checkpoint/feature_extraction/yolo11x-seg.pt"
  rcnn_checkpoint: "./checkpoint/feature_extraction/fasterrcnn_resnet101.pth"
  vocab_path: "./checkpoint/vocab/vocab_Flickr8k.pkl"
  train_data_path: "path/to/train/data"
  val_data_path: "path/to/val/data"
  save_path: "./checkpoints/model/"
